const Map<String, List<String>> activityTypeMap = {
  'All Activities': [],
  'Feed': ['breastFeed', 'bottleFeed', 'solids'],
  'Pump': ['pumpTotal', 'pumpLeftRight'],
  'Sleep': ['sleep'],
  'Diaper': ['diaper'],
  'Growth': ['growth'],
  'Baby Firsts': ['babyFirsts'],
  'Teething': ['teething'],
  'Medication': ['medication'],
  'Fever': ['fever'],
  'Vaccination': ['vaccination'],
  'Doctor Visit': ['doctorVisit'],
};

const Map<String, String> activityIconMap = {
  'breastFeed': 'feed',
  'bottleFeed': 'feed',
  'solids': 'feed',
  'pumpTotal': 'pump',
  'pumpLeftRight': 'pump',
  'sleep': 'sleep',
  'diaper': 'diaper',
  'growth': 'growth',
  'babyFirsts': 'babyFirsts',
  'teething': 'teething',
  'medication': 'medication',
  'fever': 'fever',
  'vaccination': 'vaccination',
  'doctorVisit': 'doctorVisit',
};
