const Map<String, String> isoToothDescriptions = {
  '51': 'Upper Right Central Incisor',
  '52': 'Upper Right Lateral Incisor',
  '53': 'Upper Right Canine',
  '54': 'Upper Right First Molar',
  '55': 'Upper Right Second Molar',
  '61': 'Upper Left Central Incisor',
  '62': 'Upper Left Lateral Incisor',
  '63': 'Upper Left Canine',
  '64': 'Upper Left First Molar',
  '65': 'Upper Left Second Molar',
  '71': 'Lower Left Central Incisor',
  '72': 'Lower Left Lateral Incisor',
  '73': 'Lower Left Canine',
  '74': 'Lower Left First Molar',
  '75': 'Lower Left Second Molar',
  '81': 'Lower Right Central Incisor',
  '82': 'Lower Right Lateral Incisor',
  '83': 'Lower Right Canine',
  '84': 'Lower Right First Molar',
  '85': 'Lower Right Second Molar',
};
