// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUJbiFTgh1lpyzBbMWmsCV6baU922IHgM',
    appId: '1:880549897239:web:f0df90dbb5acec6a452852',
    messagingSenderId: '880549897239',
    projectId: 'baby-sara',
    authDomain: 'baby-sara.firebaseapp.com',
    storageBucket: 'baby-sara.firebasestorage.app',
    measurementId: 'G-YD9TT8VLTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl7frXlsgKknlL-65TcHhKV0WaWqg8gI0',
    appId: '1:880549897239:android:56319d3d2748a31c452852',
    messagingSenderId: '880549897239',
    projectId: 'baby-sara',
    storageBucket: 'baby-sara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGPmYmUF4xihsi2qybToeznBj-_2tcDUE',
    appId: '1:880549897239:ios:d112ec4a34ec5397452852',
    messagingSenderId: '880549897239',
    projectId: 'baby-sara',
    storageBucket: 'baby-sara.firebasestorage.app',
    iosBundleId: 'com.suleymansurucu.babysara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGPmYmUF4xihsi2qybToeznBj-_2tcDUE',
    appId: '1:880549897239:ios:9f96a92d2fe3cf93452852',
    messagingSenderId: '880549897239',
    projectId: 'baby-sara',
    storageBucket: 'baby-sara.firebasestorage.app',
    iosBundleId: 'com.example.flutterSaraBabyTrackerAndSound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUJbiFTgh1lpyzBbMWmsCV6baU922IHgM',
    appId: '1:880549897239:web:cdd3e2a7b43f012a452852',
    messagingSenderId: '880549897239',
    projectId: 'baby-sara',
    authDomain: 'baby-sara.firebaseapp.com',
    storageBucket: 'baby-sara.firebasestorage.app',
    measurementId: 'G-QLXCXJJY9Z',
  );
}
